### ISSUE TITLE
Specific files not reducing due to "invalid type promotion"

### ISSUE THREAD

**Issue by jefrbunn** [neutrons/PyRS#471]
While attempting to reduce specific files I am met with an error:

neXus files: 1322,1326,1367 - all part of IPTS-22091

when running a manual reduction as:
`/SNS/software/PyRS/reduce_HB2B.sh /HFIR/HB2B/IPTS-22091/nexus/HB2B_1322.nxs.h5 /SNS/users/mjb/tmp
`

I received the traceback error:

```
FrameworkManager-[Notice] Welcome to Mantid 5.0.0
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid5.0
DownloadInstrument-[Notice] All instrument definitions up to date
reduce_HB2B-[Notice] Creating subscans from /HFIR/HB2B/IPTS-22091/nexus/HB2B_1322.nxs.h5 into project file /SNS/users/mjb/tmp/HB2B_1322.h5
LoadEventNexus-[Notice] LoadEventNexus started
LoadParameterFile-[Error] Error in execution of algorithm LoadParameterFile:
LoadParameterFile-[Error] File not found: /opt/mantid50/instrument/NRSF2_Parameters.xml. Unable to parse File: in "/opt/mantid50/instrument/NRSF2_Parameters.xml"
LoadParameterFile-[Error] Error in execution of algorithm LoadParameterFile:
LoadParameterFile-[Error] File not found: /opt/mantid50/instrument/NRSF2_Parameters.xml. Unable to parse File: in "/opt/mantid50/instrument/NRSF2_Parameters.xml"
LoadIDFFromNexus-[Notice] No correction parameter file applies to the date for correction file.
LoadEventNexus-[Notice] Filtering out events when the run was marked as paused. Set the loadeventnexus.keeppausedevents configuration property to override this.
LoadEventNexus-[Notice] LoadEventNexus successful, Duration 4.35 seconds
RemoveLogs-[Notice] RemoveLogs started
RemoveLogs-[Notice] RemoveLogs successful, Duration 0.00 seconds
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
TypeError: invalid type promotion

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/SNS/software/PyRS/build/scripts-2.7/reduce_manual_HB2B.py", line 133, in <module>
    reduce_hidra_workflow(options)
  File "/SNS/software/PyRS/build/scripts-2.7/reduce_manual_HB2B.py", line 85, in reduce_hidra_workflow
    save_project_file=user_options.savecounts)
  File "/SNS/software/PyRS/build/scripts-2.7/reduce_manual_HB2B.py", line 39, in _nexus_to_subscans
    hydra_ws = converter.convert(use_mantid=False)
  File "/SNS/software/PyRS/build/lib/pyrs/core/nexus_conversion.py", line 494, in convert
    sub_runs = self.split_events_sub_runs()
  File "/SNS/software/PyRS/build/lib/pyrs/core/nexus_conversion.py", line 359, in split_events_sub_runs
    event_id_array.size)
  File "/SNS/software/PyRS/build/lib/pyrs/core/nexus_conversion.py", line 321, in _generate_subrun_event_indices
    subrun_pulseindex_array = np.searchsorted(pulse_time_array, self._splitter.times)
  File "/usr/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 1075, in searchsorted
    return _wrapfunc(a, 'searchsorted', v, side=side, sorter=sorter)
  File "/usr/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: invalid type promotion
```

**Comment by peterfpeterson** [comment]
The final time in the splitter is a nan.

**Comment by peterfpeterson** [comment]
It is in [these lines](https://github.com/neutrons/PyRS/blob/master/pyrs/core/nexus_conversion.py#L129-L131):
```python
        # Check the ending
        if curr_sub_run > 0:
            # In case the stop (scan_index = 0) is not recorded
            sub_run_time_list.append(np.nan)
```
