### ISSUE TITLE
nexus file fails to reduce if scan_index =1

### ISSUE THREAD

**Issue by jefrbunn** [neutrons/PyRS#490]
We made a single subrun peak nexus file and it fails to reduce in autoreduce with the error: 

`REDUCTION: invalid value encountered in true_divide`

I see a similar error in the manual reduce as well. This prevent us from fitting a single subrun file. 

A good run to check is run 1627.

**Comment by peterfpeterson** [comment]
```python
reduce_manual_HB2B.py /HFIR/HB2B/IPTS-9586/nexus/HB2B_1627.nxs.h5 <outputdir>
```
works just fine on the tip of current `master`. I haven't checked against the reduction GUI.

**Comment by jefrbunn** [comment]
seem the issue is in the reduced file:

```
Traceback (most recent call last):
  File "/SNS/software/PyRS/build/lib/pyrs/interface/peak_fitting/fitpeakswindow.py", line 216, in axis_1d_changed
    o_plot.plot_1d()
  File "/SNS/software/PyRS/build/lib/pyrs/interface/peak_fitting/plot.py", line 269, in plot_1d
    y_axis_name)
  File "/SNS/software/PyRS/build/lib/pyrs/interface/ui/diffdataviews.py", line 168, in plot_scatter
    y_label=y_label)
  File "/SNS/software/PyRS/build/lib/pyrs/interface/ui/mplgraphicsview1d.py", line 213, in add_plot
    markersize=markersize)
  File "/SNS/software/PyRS/build/lib/pyrs/interface/ui/mplgraphicsview1d.py", line 821, in add_main_plot
    delta_x = vec_x[1] - vec_x[0]
IndexError: index 1 is out of bounds for axis 0 with size 1
/SNS/software/PyRS/pyrs.sh: line 13: 91255 Aborted                 (core dumped) QT_API=pyqt5 PYTHONPATH=$DIREC/build/lib $MANTIDPYTHON --classic $DIREC/build/scripts-3.6/pyrsplot
```

**Comment by fanchercm** [comment]
William added a patch to check if the user loaded a project file with a single scan. 
delta_x is used to define the x limit for peak fit parameter visualization.
