### ISSUE TITLE
Strain/Stress Viewer not working on analysis

### ISSUE THREAD

**Issue by rosswhitfield** [neutrons/PyRS#504]
Two problems,

1) By default PyRS uses Mantid 5.0, and in that version you get the following error when you load a HidraWorkspace in the Strain?Stress Viewer
```
Traceback (most recent call last):
  File "/SNS/software/PyRS/build/lib/pyrs/interface/strainstressviewer/strain_stress_view.py", line 39, in openFileDialog
    self.parent.update_plot()
  File "/SNS/software/PyRS/build/lib/pyrs/interface/strainstressviewer/strain_stress_view.py", line 369, in update_plot
    plot_param=self.plot_select.get_plot_param()))
  File "/SNS/software/PyRS/build/lib/pyrs/interface/strainstressviewer/strain_stress_view.py", line 290, in set_ws
    self.strainSliceViewer = StrainSliceViewer(ws, parent=self).view
  File "/SNS/software/PyRS/build/lib/pyrs/interface/strainstressviewer/strain_stress_view.py", line 201, in __init__
    self.view.data_view.mpl_toolbar.peaksOverlayClicked.disconnect()
AttributeError: 'SliceViewerView' object has no attribute 'data_view'
./pyrs.sh: line 13: 67585 Aborted                 (core dumped) QT_API=pyqt5 PYTHONPATH=$DIREC/build/lib $MANTIDPYTHON --classic $DIREC/build/scripts-3.6/pyrsplot
```
This is because of internal changes to SliceViewer that happened between the release version and the `master` version which this viewer was developed on.

2) The Strain/Stress viewer fails on the most recent version of Mantid nightly since [this](https://github.com/mantidproject/mantid/pull/28832) was merged.

```
Traceback (most recent call last):
  File "/home/rwp/src/PyRS/pyrs/interface/strainstressviewer/strain_stress_view.py", line 39, in openFileDialog
    self.parent.update_plot()
  File "/home/rwp/src/PyRS/pyrs/interface/strainstressviewer/strain_stress_view.py", line 368, in update_plot
    self.viz_tab.set_ws(self.model.get_field_md(direction=self.plot_select.get_direction(),
  File "/home/rwp/src/PyRS/pyrs/interface/strainstressviewer/strain_stress_view.py", line 290, in set_ws
    self.strainSliceViewer = StrainSliceViewer(ws, parent=self).view
  File "/home/rwp/src/PyRS/pyrs/interface/strainstressviewer/strain_stress_view.py", line 200, in __init__
    super().__init__(ws, parent=parent)
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/presenter.py", line 63, in __init__
    self.new_plot()
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/presenter.py", line 80, in new_plot_MDE
    self.model.get_ws(slicepoint=self.get_slicepoint(),
  File "/home/rwp/src/mantid/qt/python/mantidqt/widgets/sliceviewer/model.py", line 156, in get_ws_MDE
    return BinMD(InputWorkspace=self._get_ws(), OutputWorkspace=self._rebinned_name, **params)
  File "/home/rwp/src/mantid/Framework/PythonInterface/mantid/simpleapi.py", line 1136, in algorithm_wrapper
    algm.execute()
RuntimeError: Cannot perform axis-aligned binning on a MDHistoWorkspace. Please use non-axis aligned binning.
```

**Comment by rosswhitfield** [comment]
We can't use the SliceViewer in Mantid 5.0 because the particular way it's launched (it always launches it in a separate window), we need to use nightly. So I will fix the second problem.
