### ISSUE TITLE
Reading XRAY raw TIFF

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#51]
File: LaB6_10kev_35deg-00004.tif ....
```
Traceback (most recent call last):
  File "./tests/Quick_Calibration_v2.py", line 167, in <module>
    engine, pyrs_reducer, mantid_reducer = create_instrument(hb2b_file_name, False, 2048)
  File "./tests/Quick_Calibration_v2.py", line 128, in create_instrument
    target_dimension=pixel_number, load_to_workspace=True)
  File "/home/wzz/Projects/PyRS/build/lib.linux-x86_64-2.7/pyrs/core/reductionengine.py", line 91, in load_data
    load_to_workspace=load_to_workspace)
  File "/home/wzz/Projects/PyRS/build/lib.linux-x86_64-2.7/pyrs/core/reductionengine.py", line 184, in _load_tif_image
    ''.format(image_2d_data.shape))
RuntimeError: Current algorithm can only handle 2048 x 2048 TIFF but not of size (4, 2048, 2048)
```

**Comment by peterfpeterson** [comment]
This is no longer relevant
