### ISSUE TITLE
UI crashes when saving peak fit results

### ISSUE THREAD

**Issue by fanchercm** [neutrons/PyRS#512]
Peak fitting crashes when a users tries to save peak fit results into a project file that already contains a peak collection. This error occurs if a user saves peak fitting twice, or tries to save peak fit results into a project file that already contains the peak collections.

Example datafile is /HFIR/HB2B/IPTS-25894/shared/HB2B_1610.h5

Traceback (most recent call last):
  File "/SNS/software/PyRS/build/lib/pyrs/interface/peak_fitting/fitpeakswindow.py", line 154, in save
    o_handler.save()
  File "/SNS/software/PyRS/build/lib/pyrs/interface/peak_fitting/event_handler.py", line 31, in save
    self.save_fit_result(self.parent.current_hidra_file_name)
  File "/SNS/software/PyRS/build/lib/pyrs/interface/peak_fitting/event_handler.py", line 42, in save_fit_result
    project_h5_file.write_peak_parameters(peak)
  File "/SNS/software/PyRS/build/lib/pyrs/projectfile/file_object.py", line 710, in write_peak_parameters
    single_peak_entry.create_dataset(HidraConstants.SUB_RUNS, data=fitted_peaks.sub_runs)
  File "/usr/lib64/python3.6/site-packages/h5py/_hl/group.py", line 109, in create_dataset
    self[name] = dset
  File "/usr/lib64/python3.6/site-packages/h5py/_hl/group.py", line 277, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)
/SNS/software/PyRS/pyrs.sh: line 13: 80110 Aborted                 (core dumped) QT_API=pyqt5 PYTHONPATH=$DIREC/build/lib $MANTIDPYTHON --classic $DIREC/build/scripts-3.6/pyrsplot

**Comment by rosswhitfield** [comment]
So the correct behaviour when someone saves the fitted peaks would be first to remove all existing peaks in the file then write out the newly fitted ones.

**Comment by fanchercm** [comment]
@rosswhitfield Yes, the preferred mechanism is to remove the existing peak collections and write the peak collections for the "new" fitted results
