### ISSUE TITLE
Peak Fit Result component crashes UI when empty

### ISSUE THREAD

**Issue by SmithRWORNL** [neutrons/PyRS#517]
When in the Peak Fitting window, trying to interact with any of the controls in the Peak Fit Result component causes the UI to crash with the following error:

Traceback (most recent call last):
  File "/home/r8s/git/PyRS/pyrs/interface/peak_fitting/fitpeakswindow.py", line 262, in fit_table_radio_buttons
    o_table.initialize_table()
  File "/home/r8s/git/PyRS/pyrs/interface/peak_fitting/fit_table.py", line 113, in initialize_table
    columns_names = self._get_list_of_columns()
  File "/home/r8s/git/PyRS/pyrs/interface/peak_fitting/fit_table.py", line 146, in _get_list_of_columns
    _peak_collection = self.fit_result.peakcollections[0]
AttributeError: 'NoneType' object has no attribute 'peakcollections'
Aborted (core dumped)

Controls in this component should be disabled until data exists for them to use.

**Comment by peterfpeterson** [comment]
This was already fixed
