### ISSUE TITLE
Can't change colormap in Stress/Strain viewer

### ISSUE THREAD

**Issue by rosswhitfield** [neutrons/PyRS#543]
Two problems

1. The colormap combobox is unclickable
2. If the colormap is changed in the properties toolbar it crashes as
```
Traceback (most recent call last):
  File "/opt/mantidnightly/lib/mantidqt/widgets/colorbar/colorbar.py", line 131, in cmap_index_changed
    self.cmap_changed(self.cmap.currentText(), self.crev.isChecked())
  File "/opt/mantidnightly/lib/mantidqt/widgets/colorbar/colorbar.py", line 139, in cmap_changed
    self.colorbar.mappable.set_cmap(name)
  File "/usr/lib64/python3.6/site-packages/matplotlib/cm.py", line 328, in set_cmap
    cmap = get_cmap(cmap)
  File "/usr/lib64/python3.6/site-packages/matplotlib/cm.py", line 168, in get_cmap
    % (name, ', '.join(sorted(cmap_d))))
```

**Comment by jefrbunn** [comment]
```
Also i see this error wTraceback (most recent call last):
  File "/opt/mantidnightly/lib/mantidqt/widgets/colorbar/colorbar.py", line 131, in cmap_index_changed
    self.cmap_changed(self.cmap.currentText(), self.crev.isChecked())
  File "/opt/mantidnightly/lib/mantidqt/widgets/colorbar/colorbar.py", line 139, in cmap_changed
    self.colorbar.mappable.set_cmap(name)
  File "/usr/lib64/python3.6/site-packages/matplotlib/cm.py", line 328, in set_cmap
    cmap = get_cmap(cmap)
  File "/usr/lib64/python3.6/site-packages/matplotlib/cm.py", line 168, in get_cmap
    % (name, ', '.join(sorted(cmap_d))))
ValueError: Colormap  is not recognized. Possible values are: Accent, Accent_r, Blues, Blues_r, BrBG, BrBG_r, BuGn, BuGn_r, BuPu, BuPu_r, CMRmap, CMRmap_r, Dark2, Dark2_r, GnBu, GnBu_r, Greens, Greens_r, Greys, Greys_r, OrRd, OrRd_r, Oranges, Oranges_r, PRGn, PRGn_r, Paired, Paired_r, Pastel1, Pastel1_r, Pastel2, Pastel2_r, PiYG, PiYG_r, PuBu, PuBuGn, PuBuGn_r, PuBu_r, PuOr, PuOr_r, PuRd, PuRd_r, Purples, Purples_r, RdBu, RdBu_r, RdGy, RdGy_r, RdPu, RdPu_r, RdYlBu, RdYlBu_r, RdYlGn, RdYlGn_r, Reds, Reds_r, Set1, Set1_r, Set2, Set2_r, Set3, Set3_r, Spectral, Spectral_r, Wistia, Wistia_r, YlGn, YlGnBu, YlGnBu_r, YlGn_r, YlOrBr, YlOrBr_r, YlOrRd, YlOrRd_r, afmhot, afmhot_r, autumn, autumn_r, binary, binary_r, bone, bone_r, brg, brg_r, bwr, bwr_r, cividis, cividis_r, cool, cool_r, coolwarm, coolwarm_r, copper, copper_r, cubehelix, cubehelix_r, flag, flag_r, gist_earth, gist_earth_r, gist_gray, gist_gray_r, gist_heat, gist_heat_r, gist_ncar, gist_ncar_r, gist_rainbow, gist_rainbow_r, gist_stern, gist_stern_r, gist_yarg, gist_yarg_r, gnuplot, gnuplot2, gnuplot2_r, gnuplot_r, gray, gray_r, hot, hot_r, hsv, hsv_r, inferno, inferno_r, jet, jet_r, magma, magma_r, nipy_spectral, nipy_spectral_r, ocean, ocean_r, pink, pink_r, plasma, plasma_r, prism, prism_r, rainbow, rainbow_r, seismic, seismic_r, spring, spring_r, summer, summer_r, tab10, tab10_r, tab20, tab20_r, tab20b, tab20b_r, tab20c, tab20c_r, terrain, terrain_r, viridis, viridis_r, winter, winter_r
hen trying to change now:
```

**Comment by rosswhitfield** [comment]
This appears to be an upstream bug and will need to be fixed in Mantid

**Comment by peterfpeterson** [comment]
This was fixed upstream in mantid
